#!/bin/bash

set -e

command="terraform plan -out=plan"
IFS=', ' read -r -a files <<< "$1"

for filename in "${files[@]}"
do
    while read -r line; do
        if [[ "$line" =~ ^resource ]]; then
            resource_type=$(echo $line | cut -d '"' -f 2)
            resource_name=$(echo $line | cut -d '"' -f 4)
            command="$command -target=$resource_type.$resource_name"
        fi
    done < "$filename"
done

echo $command
eval $command | landscape